### ISSUE TITLE
Health endpoint

### ISSUE THREAD

**Issue by tolleiv** [AOEpeople/gitlab-crucible-bridge#1]
When deploying the system to some sort of production cluster, it's necessary to monitor it. Therefore it would be nice to have some endpoint which can be used to determine whether the service is functional and ready to received webhook data or not.

**Comment by Dbzman** [comment]
I think it makes most sense to consider the application as healthy if the number of downloaded Crucible projecs is > 0. I'll implement something. :)

**Comment by carstenlenz** [comment]
So your application is not healthy if no one has called it yet?

**Comment by Dbzman** [comment]
I'm not talking about calls to the application.
When the application starts it downloads a list of projects from Crucible. (to have a mapping from the Git url to the Crucible project ID used for triggering the sync) These get cached in memory. It's the "cache" I refer to. :)

**Comment by carstenlenz** [comment]
Ok I see :)
Then maybe combine with "last update timestamp not older than X"

**Comment by Dbzman** [comment]
Good point! 👍

**Comment by Dbzman** [comment]
Added the basic check (without the timestamp) in 1.1.0
